### PR TITLE
chore: specify package manager

### PR DESCRIPTION
**Pull request by himself65**
```shell
opencat.app git:(main) ✗ yarn
Usage Error: This project is configured to use pnpm

$ yarn ...
```

### CODE REVIEW

**Comment by anaughtyboy** [comment]
maybe the better way is ignoring the "block" files within the porject root directory.

**Comment by himself65** [comment]
> maybe the better way is ignoring the "block" files within the porject root directory.


packageManager is node.js built-in feature since 16


https://nodejs.org/dist/latest-v18.x/docs/api/all.html#all_packages_packagemanager

**Comment by anaughtyboy** [comment]
> packageManager is node.js built-in feature since 16

yeah, I known that. I mean that there're many package managers, then maybe the better way is that let the coder to choose his/her preferring one.

**Comment by himself65** [comment]
> > packageManager is node.js built-in feature since 16
> 
> yeah, I known that. I mean that there're many package managers, then maybe the better way is that let the coder to choose his/her preferring one.

I'm speechless as to what you say

**Pull request merged**
