### PR TITLE
Redesign OpenCat website

### PR DESCRIPTION
**Pull request by Xatloon**
## Preview
- **Demo at: https://opencat.xatloon.me/**

- [PageSpeed Insights Report from Oct 12, 2023, 1:26:07 PM](https://pagespeed.web.dev/analysis/https-opencat-xatloon-me/xor94klsju?form_factor=mobile)

pagespeed

### After
lightdark

**Show More**

<details>
<summary>Smart App Banners</summary>
smart app banner
</details>

<details>
<summary>Menu</summary>
header
</details>

<details>
<summary>Sections</summary>
screenshots
features
resources
morebybaye
</details>

### Before
before

## Major changes
Add navigation menu, `Screenshots`, `Features` & `More by Baye` sections, `Smart App Banners`. 
Fix issue in dark mode and layout.
Adjust some style, remove unused code and garish decoration.

### Feat
- add `Smart App Banners` - 5863f8adde15b157349ea090d54e3632d2f17afa 5a2bb3ad821cb9d707cc2ccd4a397aab5b753f55 b0129af66915762f4424e4f848a458cbe13af0d0
- add `Header` component
  - add Theme Toggle - 8065f677713799d1dec9008f91892642786b0b4d
  - add Navigation menu - 1ea8ffd270df5a32606a9daf085ea5bddca6e765
  - add Logo
- add `Footer` component - 8cdd77d31d35b70b489fcd376f806f47697de190
- add Screenshots section - a0ce0309f9507102025130c18a2e69715ca13289
- add More by Baye section - 44bccdb9cf27463a8de41c2f5eb05c69c2b76803
- add Features section - 2a785d73b45200f73d2e9de8040ae9756451e2c1

### Fix
- fix some issue in dark mode - 609618dabc23d935a559cd762869b86f6c91dc6f da17c34faeec071f4a5660ca15e90548ce4ca04e 514bec111d0401f9a109e8e75f7f68873e7eb99b 6e76229179fcdf8063ea5bc16989cc210e01c98f 276dac1783d399ff8b52beafd5dfb2af89ff5e5d
- fix some issue in layout - 971389c963ea40347faece17aff5f306b4806545

### Build
- update dependencies - 00a17496f41077ba7db13a46bef67290da2e43f7 7e0076135a1e738495b2fbbbf9fa91232a9ae699

### Misc
- add required version description - #26 
- etc.

### CODE REVIEW

**Comment by Xatloon** [comment]
@waylybaye

**Comment by waylybaye** [comment]
哇哦，非常感谢！

**Comment by Xatloon** [comment]
> 哇哦，非常感谢！

🫡

**Comment by douseful** [comment]
发现个小问题，顶部的这俩按钮鼠标悬停时，鼠标图标并没有改变
image

**Comment by yetone** [comment]
牛逼啊！👍

**Comment by Xatloon** [comment]
> 发现个小问题，顶部的这俩按钮鼠标悬停时，鼠标图标并没有改变
> 
> image
> 
> 

My bad, should use `<button>` instead of `<div>`.

**Comment by teeerrytan** [comment]
Commit records are pretty clear and elegant. Thanks for the effect. 🫡

**Comment by LaoshuBaby** [comment]
> “什么？真的会有人替我重写代码”

绝对算互联网好人好事了（尤其是git commit message风格还这么conventional，惭愧了）

**Comment by ddzhj** [comment]
不仅仅是好人好事，是**匠心独运**

**Comment by henter** [comment]
太赞了 👍

**Comment by loongtex** [comment]
简直配享太庙了

**Comment by saifeiLee** [comment]
salute

**Comment by waylybaye** [comment]
发现个小问题：FAQ 页面无法用鼠标选择复制了

**Comment by waylybaye** [comment]
🤣 原来是另一个 PR，已经解决 #36 ，谢谢你们

**Pull request merged**
